version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install          # Install dependencies
  build:
    commands:
      - npm run build       # Compile TypeScript
      - npx cdk synth       # Generate CloudFormation templates
artifacts:
  files:
    - 'dist/**/*'          # Include compiled files
